# Generated by Django 4.2.11 on 2025-12-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='education',
            field=models.CharField(max_length=50),
        ),
    ]
