# Generated by Django 4.2.11 on 2025-12-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_enquiry_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
