# Generated by Django 6.0 on 2025-12-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_enquiry_education_alter_enquiry_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('MS-CIT', 'MS-CIT'), ('Tally', 'Tally'), ('Advance Excel', 'Advance Excel'), ('IOT', 'IOT'), ('Scratch', 'Scratch'), ('Other', 'Other')], max_length=50)),
                ('custom_course', models.CharField(blank=True, help_text="If 'Other' is selected", max_length=100, null=True)),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('mobile_own', models.CharField(max_length=15)),
                ('parent_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('tehsil_block', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('educational_qualification', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admitted Student',
                'verbose_name_plural': 'Admitted Students',
                'ordering': ['-admission_date'],
            },
        ),
    ]
