# Generated by Django 6.0 on 2026-01-13 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_admittedstudent_batch_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_installment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('second_installment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('third_installment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('fees_paid_to_mkcl_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('fees_paid_to_mkcl_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_detail', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Finance Detail',
                'verbose_name_plural': 'Student Finance Details',
            },
        ),
    ]
