# Generated by Django 6.0 on 2026-01-13 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_studentfinancedetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentfinancedetail",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="finance_detail", to="core.admittedstudent"
            ),
        ),
    ]
