# Generated by Django 6.0 on 2026-02-05 10:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_salesitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admittedstudent",
            name="admission_date",
            field=models.DateField(default=datetime.date.today, help_text="Date of admission"),
        ),
    ]
