# Generated by Django 6.0 on 2026-02-05 13:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_admittedstudent_admission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feepayment",
            name="payment_date",
            field=models.DateField(default=datetime.date.today, help_text="Date of payment"),
        ),
    ]
