# Generated by Django 6.0 on 2026-02-09 04:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_feepayment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_date",
            field=models.DateField(default=datetime.date.today, help_text="Date of admission"),
        ),
    ]
