# Generated by Django 6.0.1 on 2026-02-22 12:59

import core.validators
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_student_admission_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-admission_date', 'name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admittedstudent',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload student photo (JPG, PNG, GIF, max 5MB)', null=True, upload_to='student_photos/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='e.g., 3 months, 6 weeks', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, help_text='Purchase rate per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='purchased_from',
            field=models.CharField(help_text='Vendor/supplier name', max_length=200),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity in stock'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total purchase amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(help_text='Select enrolled course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='core.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload student photo (JPG, PNG, GIF, max 5MB)', null=True, upload_to='student_photos/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='studentfinancedetail',
            name='student',
            field=models.OneToOneField(help_text='Student associated with this finance record', on_delete=django.db.models.deletion.CASCADE, related_name='finance_detail', to='core.admittedstudent'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['course'], name='core_admitt_course_85b5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['admission_date'], name='core_admitt_admissi_1acf36_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['mobile_own'], name='core_admitt_mobile__694672_idx'),
        ),
        migrations.AddIndex(
            model_name='admittedstudent',
            index=models.Index(fields=['-admission_date'], name='core_admitt_admissi_52706f_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['mobile'], name='core_enquir_mobile_1deefa_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['course'], name='core_enquir_course_ad14df_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['-created_at'], name='core_enquir_created_8e0bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['student', 'payment_date'], name='core_feepay_student_00d9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_date'], name='core_feepay_payment_7504a3_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['receipt_no'], name='core_feepay_receipt_df4604_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['item_name'], name='core_salesi_item_na_45eebe_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['-created_at'], name='core_salesi_created_b07693_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course', 'admission_date'], name='core_studen_course__30e550_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='core_studen_is_acti_d09166_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone'], name='core_studen_phone_d6a640_idx'),
        ),
    ]
