# Generated by Django 6.0.1 on 2026-02-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_course_options_alter_enquiry_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admittedstudent",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
