# Generated by Django 6.0.1 on 2026-03-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_create_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('time_slot', models.CharField(choices=[('09:00-10:00', '09:00 - 10:00 AM'), ('10:00-11:00', '10:00 - 11:00 AM'), ('11:00-12:00', '11:00 - 12:00 PM'), ('12:00-13:00', '12:00 - 1:00 PM'), ('13:00-14:00', '1:00 - 2:00 PM'), ('14:00-15:00', '2:00 - 3:00 PM'), ('15:00-16:00', '3:00 - 4:00 PM'), ('16:00-17:00', '4:00 - 5:00 PM'), ('17:00-18:00', '5:00 - 6:00 PM')], help_text='Time slot for the session (1 hour each)', max_length=11)),
                ('session_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], default='Theory', help_text='Type of session - Theory or Practical', max_length=20)),
                ('batch_month', models.CharField(blank=True, db_index=True, help_text='Batch month for filtering', max_length=20, null=True)),
                ('batch_year', models.CharField(blank=True, db_index=True, help_text='Batch year for filtering', max_length=4, null=True)),
                ('course', models.CharField(blank=True, db_index=True, help_text='Course name for filtering', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this slot', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='core.admittedstudent')),
            ],
            options={
                'verbose_name': 'Student Timetable',
                'verbose_name_plural': 'Student Timetables',
                'ordering': ['day', 'time_slot'],
                'indexes': [models.Index(fields=['student'], name='core_studen_student_edca0e_idx'), models.Index(fields=['day', 'time_slot'], name='core_studen_day_c7109b_idx'), models.Index(fields=['batch_month', 'batch_year'], name='core_studen_batch_m_b04f36_idx'), models.Index(fields=['course'], name='core_studen_course_604254_idx')],
                'unique_together': {('student', 'day', 'time_slot')},
            },
        ),
    ]
