# Generated by Django 6.0.1 on 2026-03-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_create_attendance"),
    ]

    operations = [
        # Skip index renaming if they don't exist in old schema
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
