# Generated by Django 6.0.1 on 2026-03-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_create_attendance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='core_attend_student_931c39_idx',
            old_name='core_attend_student_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='core_attend_date_801bf5_idx',
            old_name='core_attend_date_idx',
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]

