# Generated by Django 6.0.1 on 2026-03-16 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_core_attend_student_date_idx_core_attend_student_931c39_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], help_text='Type of batch session', max_length=20)),
                ('time_slot', models.CharField(choices=[('08:00-09:00', '8:00 AM - 9:00 AM'), ('09:00-10:00', '9:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('11:00-12:00', '11:00 AM - 12:00 PM'), ('12:00-13:00', '12:00 PM - 1:00 PM'), ('15:00-16:00', '3:00 PM - 4:00 PM'), ('16:00-17:00', '4:00 PM - 5:00 PM'), ('17:00-18:00', '5:00 PM - 6:00 PM'), ('18:00-19:00', '6:00 PM - 7:00 PM')], db_index=True, help_text='Time slot for the batch', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=50, help_text='Maximum students in this batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['batch_type', 'time_slot'],
            },
        ),
        migrations.AddField(
            model_name='admittedstudent',
            name='practical_batch_time',
            field=models.CharField(blank=True, choices=[('08:00-09:00', '8:00 AM - 9:00 AM'), ('09:00-10:00', '9:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('11:00-12:00', '11:00 AM - 12:00 PM'), ('12:00-13:00', '12:00 PM - 1:00 PM'), ('15:00-16:00', '3:00 PM - 4:00 PM'), ('16:00-17:00', '4:00 PM - 5:00 PM'), ('17:00-18:00', '5:00 PM - 6:00 PM'), ('18:00-19:00', '6:00 PM - 7:00 PM')], help_text='Fixed daily practical batch timing', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admittedstudent',
            name='theory_batch_time',
            field=models.CharField(blank=True, choices=[('08:00-09:00', '8:00 AM - 9:00 AM'), ('09:00-10:00', '9:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('11:00-12:00', '11:00 AM - 12:00 PM'), ('12:00-13:00', '12:00 PM - 1:00 PM'), ('15:00-16:00', '3:00 PM - 4:00 PM'), ('16:00-17:00', '4:00 PM - 5:00 PM'), ('17:00-18:00', '5:00 PM - 6:00 PM'), ('18:00-19:00', '6:00 PM - 7:00 PM')], help_text='Fixed daily theory batch timing', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='practical_attendance',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave'), ('H', 'Holiday')], default='A', help_text='Practical session attendance', max_length=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='theory_attendance',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave'), ('H', 'Holiday')], default='A', help_text='Theory session attendance', max_length=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave'), ('H', 'Holiday')], default='A', max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='core_attend_student_931c39_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='core_attend_date_801bf5_idx'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course this batch belongs to (optional for common batches)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.course'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_type', 'time_slot'], name='core_batch_batch_t_7cdac2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_type', 'time_slot', 'course')},
        ),
    ]
