# Generated by Django 6.0.1 on 2026-05-03 06:23

from django.db import migrations, models


def create_afternoon_batches(apps, schema_editor):
    Batch = apps.get_model("core", "Batch")
    for batch_type in ("Theory", "Practical"):
        for time_slot in ("13:00-14:00", "14:00-15:00"):
            Batch.objects.get_or_create(
                batch_type=batch_type,
                time_slot=time_slot,
                course=None,
                defaults={"capacity": 50},
            )


def remove_afternoon_batches(apps, schema_editor):
    Batch = apps.get_model("core", "Batch")
    Batch.objects.filter(
        batch_type__in=("Theory", "Practical"),
        time_slot__in=("13:00-14:00", "14:00-15:00"),
        course=None,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_normalize_admittedstudent_full_name_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admittedstudent",
            name="practical_batch_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("08:00-09:00", "8:00 AM - 9:00 AM"),
                    ("09:00-10:00", "9:00 AM - 10:00 AM"),
                    ("10:00-11:00", "10:00 AM - 11:00 AM"),
                    ("11:00-12:00", "11:00 AM - 12:00 PM"),
                    ("12:00-13:00", "12:00 PM - 1:00 PM"),
                    ("13:00-14:00", "1:00 PM - 2:00 PM"),
                    ("14:00-15:00", "2:00 PM - 3:00 PM"),
                    ("15:00-16:00", "3:00 PM - 4:00 PM"),
                    ("16:00-17:00", "4:00 PM - 5:00 PM"),
                    ("17:00-18:00", "5:00 PM - 6:00 PM"),
                    ("18:00-19:00", "6:00 PM - 7:00 PM"),
                ],
                help_text="Fixed daily practical batch timing",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="admittedstudent",
            name="theory_batch_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("08:00-09:00", "8:00 AM - 9:00 AM"),
                    ("09:00-10:00", "9:00 AM - 10:00 AM"),
                    ("10:00-11:00", "10:00 AM - 11:00 AM"),
                    ("11:00-12:00", "11:00 AM - 12:00 PM"),
                    ("12:00-13:00", "12:00 PM - 1:00 PM"),
                    ("13:00-14:00", "1:00 PM - 2:00 PM"),
                    ("14:00-15:00", "2:00 PM - 3:00 PM"),
                    ("15:00-16:00", "3:00 PM - 4:00 PM"),
                    ("16:00-17:00", "4:00 PM - 5:00 PM"),
                    ("17:00-18:00", "5:00 PM - 6:00 PM"),
                    ("18:00-19:00", "6:00 PM - 7:00 PM"),
                ],
                help_text="Fixed daily theory batch timing",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("08:00-09:00", "8:00 AM - 9:00 AM"),
                    ("09:00-10:00", "9:00 AM - 10:00 AM"),
                    ("10:00-11:00", "10:00 AM - 11:00 AM"),
                    ("11:00-12:00", "11:00 AM - 12:00 PM"),
                    ("12:00-13:00", "12:00 PM - 1:00 PM"),
                    ("13:00-14:00", "1:00 PM - 2:00 PM"),
                    ("14:00-15:00", "2:00 PM - 3:00 PM"),
                    ("15:00-16:00", "3:00 PM - 4:00 PM"),
                    ("16:00-17:00", "4:00 PM - 5:00 PM"),
                    ("17:00-18:00", "5:00 PM - 6:00 PM"),
                    ("18:00-19:00", "6:00 PM - 7:00 PM"),
                ],
                db_index=True,
                help_text="Time slot for the batch",
                max_length=20,
            ),
        ),
        migrations.RunPython(create_afternoon_batches, remove_afternoon_batches),
    ]
