# Generated by Django 6.0.1 on 2026-05-05 13:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0030_batch_lifecycle_management"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("enquiry", "Enquiry"),
                            ("finance", "Finance"),
                            ("internal", "Internal"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("visibility", models.JSONField(blank=True, default=list)),
                ("is_pinned", models.BooleanField(default=False)),
                ("last_activity_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                (
                    "status_update",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("follow_up", "Follow-up"),
                            ("pending_docs", "Pending Documents"),
                            ("fee_discussion", "Fee Discussion"),
                            ("resolved", "Resolved"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                ("is_internal", models.BooleanField(default=True)),
                ("attachment", models.FileField(blank=True, null=True, upload_to="communication_attachments/")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentions",
                    models.ManyToManyField(
                        blank=True, related_name="mentioned_in_comments", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.commententry",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.communicationthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("admissions", "Admissions"),
                            ("financial", "Financial"),
                            ("academic", "Academic"),
                            ("operational", "Operational"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("info", "Informational"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                ("event_key", models.CharField(db_index=True, max_length=120)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link_url", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("action_label", models.CharField(blank=True, max_length=60)),
                ("due_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_read", "-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("admissions", "Admissions"),
                            ("financial", "Financial"),
                            ("academic", "Academic"),
                            ("operational", "Operational"),
                        ],
                        max_length=20,
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=False)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id", "category"],
            },
        ),
        migrations.CreateModel(
            name="ThreadParticipantState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("is_muted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_states",
                        to="core.communicationthread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="communicationthread",
            index=models.Index(fields=["scope", "status", "last_activity_at"], name="core_commun_scope_22346b_idx"),
        ),
        migrations.AddIndex(
            model_name="communicationthread",
            index=models.Index(fields=["content_type", "object_id"], name="core_commun_content_eb460d_idx"),
        ),
        migrations.AddIndex(
            model_name="commententry",
            index=models.Index(fields=["thread", "created_at"], name="core_commen_thread__e9cc14_idx"),
        ),
        migrations.AddIndex(
            model_name="commententry",
            index=models.Index(fields=["author", "created_at"], name="core_commen_author__5da875_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_read", "created_at"], name="core_notifi_recipie_4e71b2_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["category", "priority", "created_at"], name="core_notifi_categor_e2c466_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["event_key", "created_at"], name="core_notifi_event_k_00cb55_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="notificationsetting",
            unique_together={("user", "category")},
        ),
        migrations.AddIndex(
            model_name="threadparticipantstate",
            index=models.Index(fields=["user", "last_read_at"], name="core_thread_user_id_4aa48a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="threadparticipantstate",
            unique_together={("thread", "user")},
        ),
    ]
