# Generated by Django 6.0.1 on 2026-05-10 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_communicationthread_commententry_notification_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="feepayment",
                    name="core_feepay_payment_7504a3_idx",
                ),
                migrations.AlterField(
                    model_name="feepayment",
                    name="payment_date",
                    field=models.DateField(
                        db_index=True,
                        default=datetime.date.today,
                        help_text="Date of payment",
                    ),
                ),
            ],
        ),
    ]
