# Generated by Codex on 2026-05-12

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0032_remove_feepayment_core_feepay_payment_7504a3_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("receipt_no", models.CharField(editable=False, max_length=20, unique=True)),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=15)),
                ("customer_address", models.TextField(blank=True)),
                ("sale_date", models.DateField(db_index=True, default=datetime.date.today)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("UPI", "UPI"),
                            ("Card", "Card"),
                            ("Bank Transfer", "Bank Transfer"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["receipt_no"], name="core_salesr_receipt_75b4a5_idx"),
                    models.Index(fields=["sale_date"], name="core_salesr_sale_da_7f3b87_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesReceiptLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_type", models.CharField(choices=[("item", "Item"), ("service", "Service")], default="service", max_length=20)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="core.salesreceipt"),
                ),
                (
                    "sales_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipt_lines",
                        to="core.salesitem",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
