# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_inventory_c_is_acti_idx_inventory_c_is_acti_734468_idx_and_more"),
        ("core", "0033_salesreceipt_salesreceiptline"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesreceiptline",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_receipt_lines",
                to="inventory.item",
            ),
        ),
    ]
