# Generated by Django 6.0.1 on 2026-05-12 15:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_salesreceiptline_inventory_item'),
        ('inventory', '0002_rename_inventory_c_is_acti_idx_inventory_c_is_acti_734468_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Sales Entry',
                'verbose_name_plural': 'Daily Sales Entries',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('item', 'Item'), ('service', 'Service')], default='service', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameIndex(
            model_name='salesreceipt',
            new_name='core_salesr_receipt_295019_idx',
            old_name='core_salesr_receipt_75b4a5_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreceipt',
            new_name='core_salesr_sale_da_b0c40b_idx',
            old_name='core_salesr_sale_da_7f3b87_idx',
        ),
        migrations.AddField(
            model_name='dailysalesentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sales_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysalesline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.dailysalesentry'),
        ),
        migrations.AddField(
            model_name='dailysalesline',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sales_lines', to='inventory.item'),
        ),
        migrations.AddIndex(
            model_name='dailysalesentry',
            index=models.Index(fields=['sale_date'], name='core_dailys_sale_da_92545d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysalesentry',
            index=models.Index(fields=['payment_mode'], name='core_dailys_payment_629222_idx'),
        ),
    ]
