# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_dailysalesentry_dailysalesline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailysalesline",
            name="sales_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_sales_lines",
                to="core.salesreceipt",
            ),
        ),
    ]
