# Generated by Django 6.0.1 on 2026-05-16 14:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_dailysalesline_sales_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalesentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysalesentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_daily_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysalesentry',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='dailysalesentry',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_daily_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysalesline',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Purchase cost per unit frozen at time of sale', max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_sales_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='modification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_sales_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesreceiptline',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Purchase cost per unit frozen at time of sale', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysalesline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='dailysalesentry',
            unique_together={('sale_date', 'payment_mode')},
        ),
    ]
