# Generated by Django 6.0.1 on 2026-06-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_remove_sales_and_inventory"),
    ]

    operations = [
        # State-only operations for already deleted models (tables were dropped in migration 0038)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="dailysalesentry",
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name="dailysalesentry",
                    name="core_dailys_sale_da_92545d_idx",
                ),
                migrations.RemoveIndex(
                    model_name="dailysalesentry",
                    name="core_dailys_payment_629222_idx",
                ),
                migrations.RemoveField(
                    model_name="dailysalesline",
                    name="entry",
                ),
                migrations.RemoveField(
                    model_name="dailysalesline",
                    name="inventory_item",
                ),
                migrations.RemoveField(
                    model_name="dailysalesline",
                    name="sales_receipt",
                ),
                migrations.RemoveIndex(
                    model_name="salesitem",
                    name="core_salesi_item_na_45eebe_idx",
                ),
                migrations.RemoveIndex(
                    model_name="salesitem",
                    name="core_salesi_created_b07693_idx",
                ),
                migrations.RemoveField(
                    model_name="salesreceiptline",
                    name="sales_item",
                ),
                migrations.RemoveIndex(
                    model_name="salesreceipt",
                    name="core_salesr_receipt_295019_idx",
                ),
                migrations.RemoveIndex(
                    model_name="salesreceipt",
                    name="core_salesr_sale_da_b0c40b_idx",
                ),
                migrations.RemoveField(
                    model_name="salesreceiptline",
                    name="receipt",
                ),
                migrations.RemoveField(
                    model_name="salesreceiptline",
                    name="inventory_item",
                ),
                migrations.RemoveField(
                    model_name="dailysalesentry",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="dailysalesentry",
                    name="deleted_by",
                ),
                migrations.RemoveField(
                    model_name="dailysalesentry",
                    name="modified_by",
                ),
                migrations.DeleteModel(
                    name="DailySalesLine",
                ),
                migrations.DeleteModel(
                    name="SalesItem",
                ),
                migrations.RemoveField(
                    model_name="salesreceipt",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="salesreceipt",
                    name="deleted_by",
                ),
                migrations.RemoveField(
                    model_name="salesreceipt",
                    name="modified_by",
                ),
                migrations.DeleteModel(
                    name="SalesReceiptLine",
                ),
                migrations.DeleteModel(
                    name="DailySalesEntry",
                ),
                migrations.DeleteModel(
                    name="SalesReceipt",
                ),
            ],
            database_operations=[]
        ),
        # Real database operations to add indexes to student fields
        migrations.AlterField(
            model_name="admittedstudent",
            name="father_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="admittedstudent",
            name="full_name",
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="admittedstudent",
            name="mobile_own",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="admittedstudent",
            name="student_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="admittedstudent",
            name="surname",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
