# Generated by Django 6.0.1 on 2026-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_dailysalesentry_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Enable WhatsApp Bot"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("console", "Console Log (Testing)"),
                            ("meta", "Meta WhatsApp Cloud API"),
                            ("twilio", "Twilio WhatsApp API"),
                            ("custom", "Custom HTTP Gateway"),
                        ],
                        default="console",
                        max_length=20,
                    ),
                ),
                (
                    "meta_token",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Meta Access Token",
                    ),
                ),
                (
                    "meta_phone_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Meta Phone Number ID",
                    ),
                ),
                (
                    "twilio_sid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Twilio Account SID",
                    ),
                ),
                (
                    "twilio_auth_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Twilio Auth Token",
                    ),
                ),
                (
                    "twilio_from",
                    models.CharField(
                        blank=True,
                        default="whatsapp:+14155238886",
                        max_length=100,
                        null=True,
                        verbose_name="Twilio Sender Number",
                    ),
                ),
                (
                    "custom_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Custom Gateway URL",
                    ),
                ),
                (
                    "custom_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Custom Gateway Token",
                    ),
                ),
                (
                    "admission_template",
                    models.TextField(
                        default="Hello {student_name}, welcome to Shri Samarth Computer Education! Your admission for the course {course_name} has been confirmed. Your Student ID is {student_id}. Thank you!",
                        help_text="Variables allowed: {student_name}, {course_name}, {student_id}",
                    ),
                ),
                (
                    "payment_template",
                    models.TextField(
                        default="Dear {student_name}, we have received your payment of Rs. {amount} (Receipt: {receipt_no}) for the course {course_name}. Remaining fees: Rs. {remaining_fees}. Thank you! - Shri Samarth Computer Education",
                        help_text="Variables allowed: {student_name}, {amount}, {receipt_no}, {course_name}, {remaining_fees}",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp Configuration",
                "verbose_name_plural": "WhatsApp Configurations",
            },
        ),
    ]
