# Generated by Django 6.0.1 on 2026-06-11 07:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_whatsappconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappconfig",
            name="absent_template",
            field=models.TextField(
                default="Dear {student_name}, you were absent today ({date}) for the {batch_type} batch at {batch_time}. Please make sure to attend regular classes. - Shri Samarth Computer Education",
                help_text="Variables allowed: {student_name}, {date}, {batch_time}, {batch_type}",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="enquiry_template",
            field=models.TextField(
                default="Hello {student_name}, thank you for your enquiry for the course {course_name} at Shri Samarth Computer Education. We will contact you soon. Contact: 9876543210.",
                help_text="Variables allowed: {student_name}, {course_name}, {institute_name}, {contact_number}",
            ),
        ),
        migrations.CreateModel(
            name="StudentExamRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(db_index=True, max_length=200)),
                (
                    "learner_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="MKCL Learner ID or Student Registration ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("exam_date", models.DateField(db_index=True)),
                ("course", models.CharField(db_index=True, max_length=100)),
                (
                    "course_batch",
                    models.CharField(
                        db_index=True,
                        help_text="Batch month and year (e.g., January 2026)",
                        max_length=100,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("Pass", "Pass"), ("Fail", "Fail")],
                        default="Pass",
                        max_length=20,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to admitted student if registered",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_records",
                        to="core.admittedstudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Exam Record",
                "verbose_name_plural": "Student Exam Records",
                "ordering": ["-exam_date", "student_name"],
            },
        ),
    ]
