# Generated by Django 6.0.1 on 2026-05-11 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="category",
            new_name="inventory_c_is_acti_734468_idx",
            old_name="inventory_c_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="inventory_i_categor_b03a42_idx",
            old_name="inventory_i_categor_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="inventory_i_is_acti_056110_idx",
            old_name="inventory_i_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="inventory_i_current_5dd200_idx",
            old_name="inventory_i_current_idx",
        ),
        migrations.RenameIndex(
            model_name="lowstockalert",
            new_name="inventory_l_status_01dd90_idx",
            old_name="inventory_l_status_idx",
        ),
        migrations.RenameIndex(
            model_name="lowstockalert",
            new_name="inventory_l_item_id_683540_idx",
            old_name="inventory_l_item_id_idx",
        ),
        migrations.RenameIndex(
            model_name="purchase",
            new_name="inventory_p_item_id_a14275_idx",
            old_name="inventory_p_item_id_idx",
        ),
        migrations.RenameIndex(
            model_name="purchase",
            new_name="inventory_p_supplie_93a1b9_idx",
            old_name="inventory_p_supplier_idx",
        ),
        migrations.RenameIndex(
            model_name="purchase",
            new_name="inventory_p_purchas_aba9fc_idx",
            old_name="inventory_p_purchase_idx",
        ),
        migrations.RenameIndex(
            model_name="purchase",
            new_name="inventory_p_batch_n_a21777_idx",
            old_name="inventory_p_batch_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="inventory_s_item_id_384e17_idx",
            old_name="inventory_s_item_id_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="inventory_s_movemen_a71f62_idx",
            old_name="inventory_s_movement_idx",
        ),
        migrations.RenameIndex(
            model_name="supplier",
            new_name="inventory_s_is_acti_99fe06_idx",
            old_name="inventory_s_is_acti_idx",
        ),
        migrations.AlterField(
            model_name="purchase",
            name="purchase_date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
