# Generated by Django 6.0.1 on 2026-06-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_salereceipt_salereceiptline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["phone"], name="inventory_c_phone_cc89f4_idx"),
                    models.Index(fields=["name"], name="inventory_c_name_a2eb08_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="salereceipt",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to customer record (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_receipts",
                to="inventory.customer",
            ),
        ),
    ]
